import { formatBytes } from './format.js';
import { CATEGORY_LABELS, type Report } from './types.js';

const SEVERITY_ICON = { error: '🔴', warn: '🟠', info: '🔵' } as const;

/** A compact Markdown summary for PR comments, issues, Slack and posts. */
export function reportToMarkdown(report: Report): string {
  const { app, sizes } = report;
  const m = app.manifest;
  const name = m.packageName ? `${m.packageName}${m.versionName ? ` ${m.versionName}` : ''}` : app.fileName;
  const est = (e: boolean) => (e ? ' (est.)' : '');
  const target = [sizes.download.abi === 'all' ? 'all ABIs' : sizes.download.abi, sizes.download.density]
    .filter(Boolean)
    .join(', ');
  const total = report.breakdown.reduce((s, r) => s + r.compressed, 0) || 1;

  const lines = [
    `### 📦 App size: ${name}`,
    '',
    `**Download (${target}): ${formatBytes(sizes.download.bytes)}**${est(sizes.download.estimate)} · Install: ${formatBytes(sizes.install.bytes)}${est(sizes.install.estimate)} · ${app.artifact.toUpperCase()}${app.js?.engine === 'hermes' ? ' · Hermes' : ''}${app.code.minified === false ? ' · R8 off' : ''}`,
    '',
    '| Category | Size | % |',
    '|---|---:|---:|',
    ...[...report.breakdown]
      .sort((a, b) => b.compressed - a.compressed)
      .map((r) => `| ${r.category === 'js' && app.js?.engine === 'hermes' ? 'JS bundle (Hermes)' : CATEGORY_LABELS[r.category]} | ${formatBytes(r.compressed)} | ${((r.compressed / total) * 100).toFixed(1)}% |`),
  ];

  if (report.findings.length > 0) {
    lines.push('', '**Quick wins**', '');
    for (const f of report.findings) {
      const saves = f.savings ? ` (saves ${f.savings.estimate ? '~' : ''}${formatBytes(f.savings.bytes)})` : '';
      lines.push(`- ${SEVERITY_ICON[f.severity]} ${f.title}${saves}`);
    }
    if (report.totals.savingsBytes > 0 && !m.debuggable) {
      lines.push('', `**Estimated total savings: ~${formatBytes(report.totals.savingsBytes)}**`);
    }
  }
  lines.push('', '<sub>Generated by [rn-size-check](https://github.com/MuhammadHamza47/rn-size-check)</sub>');
  return lines.join('\n');
}
